version: '3.4'

services:
  newsanalysis:
    image: newsanalysis
    build:
      context: .
      dockerfile: ./Dockerfile
  postgres:
  # We can replace the image with the following to use the pgvector/pgvector:pg16 image
  # pgvector/pgvector:pg16 
    image: pgvector/pgvector:pg16 
    # image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsanalysis
    ports:
      - "5432:5432"
